# ─────────────────────────────────────────────────────────────────────────────
# Default (no profile) – for local development on your laptop
# Spring will bind to localhost:9002 and connect to a “real” Mongo at localhost.
# ─────────────────────────────────────────────────────────────────────────────
server:
  port: 9002
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: price-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/price-db
      auto-index-creation: true

---
# ─────────────────────────────────────────────────────────────────────────────
# “docker” profile – only active when SPRING_PROFILES_ACTIVE=docker
# Connects to the container named “mongo” and listens on port 8080.
# ─────────────────────────────────────────────────────────────────────────────
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://mongo:27017/price-db       # ← use “mongo” here
      auto-index-creation: true

server:
  port: 8080
